[versions]
kotlin-version = "1.6.20"
kotlinx-html-version = "0.7.5"
coroutines-version = "1.6.0"
atomicfu-version = "0.17.1"
serialization-version = "1.3.2"
validator-version = "0.8.0"
ktlint-version = "3.6.0"

netty-version = "4.1.74.Final"
netty-tcnative-version = "2.0.45.Final"

jetty-version = "9.4.45.v20220203"
jetty-alpn-api-version = "1.1.3.v20160715"
jetty-alpn-boot-version = "8.1.13.v20181017"

tomcat-version = "9.0.62"

apache-version = "4.1.5"
apacheds-version = "2.0.0-M24"
okhttp-version = "4.9.3"

json-simple-version = "1.1.1"
gson-version = "2.9.0"
jackson-version = "2.13.1"

junit-version = "4.13.2"
slf4j-version = "1.7.36"
logback-version = "1.2.11"

dropwizard-version = "4.2.8"
micrometer-version = "1.7.5"

jansi-version = "2.4.0"
typesafe-version = "1.4.1"

mockk-version = "1.12.0"
mokito-kotlin-version = "1.6.0"

java-jwt-version = "3.13.0"
jwks-rsa-version = "0.22.0"
mustache-version = "0.9.10"
freemarker-version = "2.3.31"
pebble-version = "3.1.5"
velocity-version = "2.3"
velocity-tools-version = "3.1"
webjars-locator-version = "0.48"
webjars-jquery-version = "3.3.1"
thymeleaf-version = "3.0.15.RELEASE"
javax-servlet-version = "4.0.1"

node-fetch-version = "2.6.7"
abort-controller-version = "3.0.0"
ws-version = "8.5.0"
xmlutil-version = "0.84.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-version" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin-version" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-version" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }

kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu-version" }

kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "coroutines-version" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-version" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines-version" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "coroutines-version" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization-version" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-version" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization-version" }

kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinx-html-version" }

netty-handler = { module = "io.netty:netty-handler", version.ref = "netty-version" }
netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty-version" }
netty-transport-native-kqueue = { module = "io.netty:netty-transport-native-kqueue", version.ref = "netty-version" }
netty-transport-native-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty-version" }
netty-tcnative = { module = "io.netty:netty-tcnative", version.ref = "netty-tcnative-version" }
netty-tcnative-boringssl-static = { module = "io.netty:netty-tcnative-boringssl-static", version.ref = "netty-tcnative-version" }

tomcat-catalina = { module = "org.apache.tomcat:tomcat-catalina", version.ref = "tomcat-version" }
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat-version" }

jetty-alpn-api = { module = "org.eclipse.jetty.alpn:alpn-api", version.ref = "jetty-alpn-api-version" }
jetty-client = { module = "org.eclipse.jetty:jetty-client", version.ref = "jetty-version" }
jetty-http2-server = { module = "org.eclipse.jetty.http2:http2-server", version.ref = "jetty-version" }
jetty-http2-client = { module = "org.eclipse.jetty.http2:http2-client", version.ref = "jetty-version" }
jetty-http2-client-transport = { module = "org.eclipse.jetty.http2:http2-http-client-transport", version.ref = "jetty-version" }
jetty-alpn-boot = { module = "org.mortbay.jetty.alpn:alpn-boot", version.ref = "jetty-alpn-boot-version" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty-version" }
jetty-servlets = { module = "org.eclipse.jetty:jetty-servlets", version.ref = "jetty-version" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet", version.ref = "jetty-version" }
jetty-alpn-server = { module = "org.eclipse.jetty:jetty-alpn-server", version.ref = "jetty-version" }
jetty-alpn-openjdk8-server = { module = "org.eclipse.jetty:jetty-alpn-openjdk8-server", version.ref = "jetty-version" }
jetty-alpn-openjdk8-client = { module = "org.eclipse.jetty:jetty-alpn-openjdk8-client", version.ref = "jetty-version" }
jetty-alpn-java-server = { module = "org.eclipse.jetty:jetty-alpn-java-server", version.ref = "jetty-version" }
jetty-alpn-java-client = { module = "org.eclipse.jetty:jetty-alpn-java-client", version.ref = "jetty-version" }

json-simple = { module = "com.googlecode.json-simple:json-simple", version.ref = "json-simple-version" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson-version" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-version" }

jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi-version" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-version" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt-version" }
jwks-rsa = { module = "com.auth0:jwks-rsa", version.ref = "jwks-rsa-version" }

mockito-kotlin = { module = "com.nhaarman:mockito-kotlin", version.ref = "mokito-kotlin-version" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk-version" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-version" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
junit = { module = "junit:junit", version.ref = "junit-version" }

apache-httpasyncclient = { module = "org.apache.httpcomponents:httpasyncclient", version.ref = "apache-version" }
apacheds-server = { module = "org.apache.directory.server:apacheds-server-integ", version.ref = "apacheds-version" }
apacheds-core = { module = "org.apache.directory.server:apacheds-core-integ", version.ref = "apacheds-version" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }

dropwizard-core = { module = "io.dropwizard.metrics:metrics-core", version.ref = "dropwizard-version" }
dropwizard-jvm = { module = "io.dropwizard.metrics:metrics-jvm", version.ref = "dropwizard-version" }
micrometer = { module = "io.micrometer:micrometer-core", version.ref = "micrometer-version" }

mustache = { module = "com.github.spullara.mustache.java:compiler", version.ref = "mustache-version" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker-version" }
pebble = { module = "io.pebbletemplates:pebble", version.ref = "pebble-version" }
velocity = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity-version" }
velocity-tools = { module = "org.apache.velocity.tools:velocity-tools-generic", version.ref = "velocity-tools-version" }
webjars-locator = { module = "org.webjars:webjars-locator-core", version.ref = "webjars-locator-version" }
webjars-jquery = { module = "org.webjars:jquery", version.ref = "webjars-jquery-version" }
thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf-version" }

javax-servlet = { module = "javax.servlet:javax.servlet-api", version.ref = "javax-servlet-version" }

xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil-version" }
